
name: Detect Flaky Tests

on:
  workflow_dispatch: # Manual trigger from GitHub UI

jobs:
  flaky-tests:
    uses: ashleytoole84/flaky-test-detector/.github/workflows/flaky-test-detector.yml@v1.0.0
    with:
      repository: ashleytoole84/platform-engineer-tech-case-49378219
      workflow-name: CI
      runs-limit: 30
      branch: main
    secrets:
      github-token: ${{ secrets.FLAKY_TEST_PAT }}

  report-results:
    needs: flaky-tests
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Debug Outputs
        run: |
          echo "Raw ALL_TESTS: ${{ needs.flaky-tests.outputs.all-tests }}"
          echo "Raw FLAKY_TESTS: ${{ needs.flaky-tests.outputs.flaky-tests }}"
      - name: Display test results
        run: |
          ALL_TESTS="${{ needs.flaky-tests.outputs.all-tests }}"
          FLAKY_TESTS="${{ needs.flaky-tests.outputs.flaky-tests }}"
          echo "All Test Results:"
          if [ -n "$ALL_TESTS" ] && [ "$ALL_TESTS" != "{}" ]; then
            echo "$ALL_TESTS" | jq -r 'to_entries | .[] | "- \(.key): \(.value.pass) passes, \(.value.fail) failures"'
          else
            echo "No test results found."
          fi
          echo ""
          echo "Flaky Test Results:"
          if [ -n "$FLAKY_TESTS" ] && [ "$FLAKY_TESTS" != "{}" ]; then
            echo "$FLAKY_TESTS" | jq -r 'to_entries | .[] | "- \(.key): failed \(.value) times"'
          else
            echo "No flaky tests detected."
          fi
          echo "Check 'Fetch and parse test artifacts' step logs for additional details."
